### ISSUE TITLE
Text field value doesn't update when the initial value is nil.

### ISSUE THREAD

**Issue by vanboom** [phlipper/farbtastic-rails#1]
If the initial value of the color is nil, the text field text value does not refresh when the color picker is used.  The background of the text field will update, but the text value inside the text field does not. 

Typing in some value to start with makes it work.  

Thanks for a GREAT gem!

**Comment by phlipper** [comment]
@vanboom thanks for the report. This gem is just a simple wrapper for the Farbtastic library and bug reports should be filed at the [mattfarina/farbtastic](https://github.com/mattfarina/farbtastic) repo. Unfortunately, it doesn't look very active these days, but that is your best bet at the moment.

If/when the upstream repo releases an update, I will be sure to update this gem as well. 

Thanks again!
